[wikivoyage]
title = "Wikivoyage recommendations"
url = "https://en.wikivoyage.org/wiki/Main_Page"
entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"

[japscan]
title = "Japscan one piece"
url = "https://www.japscan.ws/manga/one-piece/"
entrySelector = ".chapters_list"
titleSelector = "a"
linkSelector = ".text-dark"
